# Generated by Django 6.0.4 on 2026-09-23 14:21

import ads.models
import django.db.models.deletion
import pulse.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_key', models.SlugField(unique=True)),
                ('name', models.CharField(help_text='Admin display name', max_length=100)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Ad Slot',
                'verbose_name_plural': 'Ad Slots',
                'ordering': ('slot_key',),
            },
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Internal name', max_length=200)),
                ('client_name', models.CharField(blank=True, help_text='Advertiser name', max_length=200)),
                ('image', pulse.fields.ProcessedImageField(blank=True, help_text='IMPORTANT: Upload images at EXACT dimensions for best results: Leaderboard 728×90px, Mobile 320×100px, Sidebar 300×250px. Images maintain aspect ratio - wrong sizes will show with black bars.', max_size=(728, 250), null=True, upload_to=ads.models.ad_image_path)),
                ('link_url', models.URLField(blank=True, max_length=1000)),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_house_ad', models.BooleanField(db_index=True, default=False, help_text='Shown when no paid ad is available for this slot')),
                ('priority', models.PositiveSmallIntegerField(default=5, help_text='Higher number = higher priority. Examples: 10=Premium clients, 5=Standard ads, 1=House ads. When multiple ads are active in the same slot, the highest priority wins. Ties are broken randomly.')),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ads', to='ads.adslot')),
            ],
            options={
                'verbose_name': 'Advertisement',
                'verbose_name_plural': 'Advertisements',
                'ordering': ('-priority', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='AdEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('impression', 'Impression'), ('click', 'Click')], db_index=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=200)),
                ('page_path', models.CharField(blank=True, max_length=200)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='ads.ad')),
            ],
            options={
                'verbose_name': 'Ad Event',
                'verbose_name_plural': 'Ad Events',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['ad', 'event_type', 'created_at'], name='ads_adevent_ad_id_14c18d_idx')],
            },
        ),
    ]
