# Generated by Django 6.0.4 on 2026-09-24 12:24

import django.db.models.deletion
import hotreports.fields
import hotreports.media_storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(choices=[('news-tip', 'News Tip'), ('story-submission', 'Submit Your Story'), ('story-feedback', 'Story Feedback'), ('tourism-listing', 'List Your Tourism Business'), ('advertising', 'Advertising Inquiry'), ('correction', 'Correction / Fact Check'), ('general', 'General Inquiry')], max_length=32)),
                ('phone', models.CharField(blank=True, max_length=80)),
                ('message', models.TextField()),
                ('handled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(db_index=True, max_length=500, unique=True)),
                ('p256dh', models.CharField(max_length=300)),
                ('auth', models.CharField(max_length=200)),
                ('user_agent', models.TextField(blank=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notification_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('-subscribed_at',),
            },
        ),
        migrations.CreateModel(
            name='StoryEpisode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_number', models.PositiveSmallIntegerField(db_index=True)),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=280)),
                ('excerpt', models.TextField(blank=True, help_text='Teaser/cliffhanger for this episode (for social media sharing)')),
                ('content', models.TextField(help_text='Full episode content')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('published', 'Published')], default='draft', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('scheduled_publish_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('views_total', models.PositiveIntegerField(db_index=True, default=0)),
                ('read_time_minutes', models.PositiveSmallIntegerField(default=5)),
                ('next_episode_teaser', models.CharField(blank=True, help_text="Hook for the next episode (e.g., 'Will Brian find out the truth?')", max_length=200)),
                ('image', hotreports.fields.ProcessedImageField(blank=True, help_text='Upload an episode image. Will be automatically resized to max 1200x800 and converted to WebP format. Saved as: episode-images/YYYY/MM/series-title-episode-N.webp', max_size=(1200, 800), null=True, upload_to=hotreports.media_storage.episode_image_path)),
                ('image_url', models.URLField(blank=True, default='', help_text='Optional external image URL', max_length=500)),
                ('image_attribution', models.CharField(blank=True, help_text="e.g., 'Tony Webster from Minneapolis, Minnesota, United States, CC BY 2.0, via Wikimedia Commons'", max_length=500)),
                ('meta_title', models.CharField(blank=True, help_text='Custom title for SEO/social (falls back to episode title)', max_length=500)),
                ('meta_description', models.TextField(blank=True, help_text='Custom description for SEO/social (falls back to excerpt)')),
                ('meta_keywords', models.CharField(blank=True, help_text="Comma-separated keywords for SEO (e.g., 'village drama, campus life, fiction')", max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'story episodes',
                'ordering': ('series', 'episode_number'),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=240, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('excerpt', models.TextField()),
                ('content', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('national', 'National'), ('politics', 'Politics'), ('business', 'Business'), ('technology', 'Technology'), ('education', 'Education'), ('health', 'Health'), ('culture-society', 'Culture & Society'), ('sports', 'Sports'), ('op-ed', 'Op-Ed'), ('africa', 'Africa'), ('world', 'World')], db_index=True, max_length=32)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('image_attribution', models.CharField(blank=True, help_text="e.g., 'Tony Webster from Minneapolis, Minnesota, United States, CC BY 2.0, via Wikimedia Commons'", max_length=500)),
                ('image', hotreports.fields.ProcessedImageField(blank=True, help_text='Upload an article image. Will be automatically resized to max 1200x630 and converted to WebP format. Saved as: article-images/YYYY/MM/slugified-title.webp', max_size=(1200, 630), null=True, upload_to=hotreports.media_storage.article_image_path)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('views_total', models.PositiveIntegerField(db_index=True, default=0)),
                ('scheduled_publish_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending review'), ('published', 'Published'), ('rejected', 'Rejected')], db_index=True, default='draft', max_length=16)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('read_time', models.PositiveSmallIntegerField()),
                ('highlight', models.CharField(blank=True, choices=[('', 'None'), ('featured', 'Featured'), ('breaking', 'Breaking News'), ('trending', 'Trending')], db_index=True, default='', help_text='Article can be featured, breaking, trending, or none', max_length=20)),
                ('meta_title', models.CharField(blank=True, help_text='Custom title for SEO/social (falls back to article title)', max_length=500)),
                ('meta_description', models.TextField(blank=True, help_text='Custom description for SEO/social (falls back to excerpt)')),
                ('meta_keywords', models.CharField(blank=True, help_text="Comma-separated keywords for SEO (e.g., 'news, politics, Uganda')", max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_articles', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authored_articles', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_articles', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='articles', to='news.tag')),
            ],
            options={
                'ordering': ('-published_at',),
                'permissions': [('can_publish_article', 'Can publish articles')],
            },
        ),
        migrations.CreateModel(
            name='ArticleViewEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('visitor_key', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=400)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_events', to='news.article')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='StoryEpisodeComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Your name', max_length=100)),
                ('email', models.EmailField(blank=True, help_text='Optional - not displayed publicly', max_length=254)),
                ('content', models.TextField(help_text='Your comment', max_length=2000)),
                ('is_approved', models.BooleanField(db_index=True, default=False, help_text='Comments require approval')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='news.storyepisode')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='news.storyepisodecomment')),
            ],
            options={
                'verbose_name_plural': 'story comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StorySeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=240, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('subtitle', models.CharField(blank=True, help_text='Tagline for the story series', max_length=500)),
                ('description', models.TextField(help_text='Brief summary of the story')),
                ('genre', models.CharField(choices=[('village_drama', 'Village Drama'), ('campus_life', 'Campus Life'), ('family', 'Family Conflict'), ('cultural', 'Cultural Stories'), ('true_life', 'True Life'), ('crime', 'Crime Mystery'), ('inspirational', 'Inspirational')], default='village_drama', max_length=20)),
                ('cover_image', hotreports.fields.ProcessedImageField(blank=True, help_text='Cover image for the story series. Saved as: story-covers/YYYY/MM/slugified-title.webp', max_size=(800, 1200), null=True, upload_to=hotreports.media_storage.story_cover_path)),
                ('cover_image_url', models.URLField(blank=True, default='', max_length=500)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], default='draft', max_length=16)),
                ('is_featured', models.BooleanField(db_index=True, default=False, help_text='Feature this series on the stories homepage')),
                ('total_episodes', models.PositiveSmallIntegerField(default=0, help_text='Auto-updated when episodes are added')),
                ('views_total', models.PositiveIntegerField(db_index=True, default=0)),
                ('meta_title', models.CharField(blank=True, help_text='Custom title for SEO/social (falls back to series title)', max_length=300)),
                ('meta_description', models.TextField(blank=True, help_text='Custom description for SEO/social (falls back to description)')),
                ('social_snippet', models.CharField(blank=True, help_text='Short teaser for social media (falls back to subtitle or description)', max_length=280)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='story_series', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'story series',
                'ordering': ('-is_featured', '-published_at', '-created_at'),
            },
        ),
        migrations.AddField(
            model_name='storyepisode',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='news.storyseries'),
        ),
        migrations.CreateModel(
            name='StoryShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('whatsapp', 'WhatsApp'), ('twitter', 'Twitter/X'), ('copy', 'Copy Link')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('episode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='news.storyepisode')),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='news.storyseries')),
            ],
            options={
                'verbose_name_plural': 'story shares',
            },
        ),
        migrations.CreateModel(
            name='StoryViewEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_key', models.CharField(db_index=True, max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_events', to='news.storyepisode')),
            ],
            options={
                'verbose_name_plural': 'story view events',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ArticleVisitorDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_key', models.CharField(db_index=True, max_length=64)),
                ('day', models.DateField(db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_days', to='news.article')),
            ],
            options={
                'ordering': ('-day', '-created_at'),
                'indexes': [models.Index(fields=['article', 'day', 'ip_address'], name='news_articl_article_d44134_idx')],
                'constraints': [models.UniqueConstraint(fields=('article', 'visitor_key', 'day'), name='news_articlevisitorday_article_visitor_day_uniq')],
            },
        ),
        migrations.CreateModel(
            name='StoryEpisodeLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_key', models.CharField(db_index=True, max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='news.storyepisode')),
            ],
            options={
                'verbose_name_plural': 'story likes',
                'unique_together': {('episode', 'visitor_key')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='storyepisode',
            unique_together={('series', 'episode_number')},
        ),
        migrations.CreateModel(
            name='StoryVisitorDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True)),
                ('visitor_key', models.CharField(db_index=True, max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_days', to='news.storyepisode')),
            ],
            options={
                'verbose_name_plural': 'story visitor days',
                'ordering': ('-day',),
                'indexes': [models.Index(fields=['episode', 'day', 'ip_address'], name='news_storyv_episode_bb02cc_idx')],
                'unique_together': {('episode', 'day', 'visitor_key')},
            },
        ),
    ]
