# Generated by Django 6.0.4 on 2026-09-23 14:21

import django.db.models.deletion
import hotreports.fields
import hotreports.media_storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TourismListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('name', models.CharField(max_length=300)),
                ('listing_type', models.CharField(choices=[('safari', 'Safari'), ('lodge', 'Lodge'), ('hotel', 'Hotel'), ('campsite', 'Campsite'), ('experience', 'Experience')], max_length=20)),
                ('tagline', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('image_attribution', models.CharField(blank=True, help_text="e.g., 'Tony Webster from Minneapolis, Minnesota, United States, CC BY 2.0, via Wikimedia Commons'", max_length=500)),
                ('image', hotreports.fields.ProcessedImageField(blank=True, help_text='Upload a tourism listing image. Will be automatically resized to max 800x600 and converted to WebP format. Saved as: tourism-images/YYYY/MM/slugified-name.webp', max_size=(800, 600), null=True, upload_to=hotreports.media_storage.tourism_image_path)),
                ('location', models.CharField(max_length=200)),
                ('price_range', models.CharField(max_length=120)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('featured', models.BooleanField(db_index=True, default=False)),
                ('website', models.URLField(blank=True, max_length=500)),
                ('phone', models.CharField(blank=True, max_length=80)),
                ('tags', models.JSONField(default=list)),
                ('meta_title', models.CharField(blank=True, help_text='Custom title for SEO/social (falls back to listing name)', max_length=500)),
                ('meta_description', models.TextField(blank=True, help_text='Custom description for SEO/social (falls back to tagline)')),
                ('meta_keywords', models.CharField(blank=True, help_text="Comma-separated keywords for SEO (e.g., 'safari, lodge, Uganda')", max_length=500)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tourism_listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
